const add = (a, b) => a + b
const subtract = (a, b) => a-b
const multiply = (a, b) => a*b
const divide = (a, b) => a/b

module.exports = {add, subtract, multiply, divide}

//an alternative to module.exports would be
    // exports.add = ...
    // exports.subtract = ...
    // exports.multiply = ...
    // exports.divide = ...